### ISSUE TITLE
Proposal regarding to tab-indentation type

### ISSUE THREAD

**Issue by GeorgeGkas** [sindresorhus/typescript-definition-style-guide#1]
I was checking the rules lately and found a point that want to discuss. In the [Checklist](https://github.com/sindresorhus/typescript-definition-style-guide#checklist) section the first bullet mentions that we have to use tab-indentation. There is a long running discussion of whether or not should tab be used as default indentation style in contrast of spaces. I prefer spaces over tabs mainly because using spaces it guaranties that the number of columns will be the same in any environment (1 space = 1 column).

I know that comes to personal preference, but most projects I have worked with prefer spaces over tabs. It would be bad DX if the whole codebase use spaces for indentation, and the definition file use tabs. This is what I propose:

- Use spaces over tabs, by default.
- Use the same indentation style that applies to the codebase (spaces or tabs).

Would you mind to explain the reasons behind the decision to apply tab indentation?

*Thank you for the effort to standardized a style guide for TS type definition files.*

**Comment by sindresorhus** [comment]
I think you're misunderstanding the purpose of this repo. It's not meant to be a general style guide. It's a style guide for *my repos* specifically. You are of course free to fork it, modify it, and use it for your own projects. I am also not going to start a discussion on tabs vs. spaces here.
