### ISSUE TITLE
Omitting `*` breaks formatting in VS Code

### ISSUE THREAD

**Issue by LinusU** [sindresorhus/typescript-definition-style-guide#10]
> - Don't prefix lines with *.

Opening this since I haven't seen this style used elsewhere, and it's breaking VS Code. Closing this issue with "it's a VS Code issue" is absolutely okay 👌 

When not prefixing lines with `*`, all empty lines get's stripped in the `@example`. It also doesn't highlight the `@example` block in the source code.

<img width="394" alt="Screenshot 2019-07-29 at 21 13 01" src="https://user-images.githubusercontent.com/189580/62079566-e9b63c80-b246-11e9-9b14-7fc2aacccc04.png">

☝️ With `*` prefix, notice the `@example` code being red, and that the popup that shows the function help has line breaks at the correct places.

👇 Without `*` prefix, notice that the `@example` has the same green color as any other comment, and that the empty lines are stripped in the help popup.

<img width="449" alt="Screenshot 2019-07-29 at 21 13 27" src="https://user-images.githubusercontent.com/189580/62079569-e9b63c80-b246-11e9-9aae-7f89113b5a2a.png">

edit: looking at the TSDoc and JSDoc repo/website, I can't find anything that says specifically that you must have them. But I also haven't found a single example that omits them 🤔 

edit2: It also breaks syntax highlighting when e.g. describing params:

<img width="572" alt="Screenshot 2019-07-29 at 21 34 35" src="https://user-images.githubusercontent.com/189580/62080550-cdb39a80-b248-11e9-92af-7e83cc37a2cd.png">
<img width="592" alt="Screenshot 2019-07-29 at 21 34 50" src="https://user-images.githubusercontent.com/189580/62080551-ce4c3100-b248-11e9-8ea5-09b4980332ea.png">

**Comment by sindresorhus** [comment]
VS Code has a lot of quirks when it comes to rendering doc comments. Hopefully one day they will switch to use https://github.com/microsoft/tsdoc (when it's more mature). TSDoc seems to handle missing `*` just fine: https://microsoft.github.io/tsdoc/ (try it there).

I would recommend opening an issue on VS Code. I have no intention to switch back to using `*`-prefixed lines.

**Comment by LinusU** [comment]
Will open issue against VS Code 👍
