### ISSUE TITLE
Preference on position of `types` in package.json

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/typescript-definition-style-guide#11]
Thanks for putting this guide together @sindresorhus.

I've long been using the package.json layout in your modules as a "source of truth" for my own modules, and I've "written that into stone" with [prettier-plugin-package](). I've recently had a PR to assert the position of `types` in package.json, and I wanted to get your take on it. Citing this portion of the guide:

- Use the name `"types"` and not `"typings"` for the TypeScript definition field in package.json.
- If the entry file in the package is named `index.js`, name the type definition file `index.d.ts` and put it in root.<br>
	You don't need to add a `types` field to package.json as TypeScript will infer it from the name.
- Add the type definition file to the `files` field in package.json.

It would seem that the only thing here missing is preference on where `types` should be positioned within package.json. What's your take on this? Do you have a preference of before X property and after Y property?

Input would be very useful and much appreciated :beer:

**Comment by sindresorhus** [comment]
It should be after all official properties, but before custom ones. So usually after `dependencies` or `devDependencies`.

**Comment by shellscape** [comment]
Thank you. Shall I open a PR to add that?

**Comment by sindresorhus** [comment]
Sure :)
